name: flutter_todo_with_synchronized_backup
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_proxy_plugin: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.2.0
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
